WinWait("[CLASS:#32770]","",10)
ControlFocus("Open","","Edit1")
Sleep(500)
ControlSetText("Open","","Edit1","D:\GIT LOCAL\automation\src\test\resources\TestData\test1.jpg")
Sleep(500)
ControlClick("Open","","Button1")